### ISSUE TITLE
Design page layout/UI

### ISSUE THREAD

**Issue by T-Muha** [T-Muha/ceas-tribunal-general-meeting-sign-in#1]
The sign-in page needs an interface matching the rest of the website. Includes changes to the html/css for layout and design. A draft could also be helpful.

**Comment by mihi-r** [comment]
I think referencing t[his page](https://tribunal.uc.edu/careerweek/representative-sign-in/representative.html) could be helpful in creating a Tribunal-themed UI. We can use the same form element styles. We can just use a different image for the background.
